# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Set up beginning
fib = [1,2]

# Iterate all Fibonacci numbers below 4 million
while fib[-1] < 4000000:
    fib.append(fib[-1]+fib[-2])

fibsum = 0

# Add all even terms
for num in filter(lambda x: x % 3 == 0, range(0,len(fib)-2)):
    fibsum += fib[num+1]

# Print out solution
print fibsum